apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-certificate
spec:
  dnsNames:
  - minio.apps.nerc-ocp-test-2.nerc.mghpcc.org
  - minio-console.apps.nerc-ocp-test-2.nerc.mghpcc.org
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-http01
  renewBefore: 360h0m0s
  secretName: minio-certificate
