apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-internal-certificate
spec:
  dnsNames:
  - '*.minio'
  duration: 2160h0m0s
  issuerRef:
    kind: Issuer
    name: minio-ca
  renewBefore: 360h0m0s
  secretName: minio-internal-certificate
