apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-ca
spec:
  isCA: true
  commonName: minio-ca
  secretName: minio-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
