apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: "minio"
  replicas: 4
  podManagementPolicy: Parallel
  template:
    spec:
      affinity:
        # Spread pods across multiple when possible
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - minio
              topologyKey: kubernetes.io/hostname
      containers:
      - name: minio
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
              secretKeyRef:
                name: minio-config
                key: MINIO_ROOT_USER

        - name: MINIO_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: minio-config
                key: MINIO_ROOT_PASSWORD

        image: quay.io/minio/minio:RELEASE.2024-10-29T16-01-48Z
        ports:
        - containerPort: 9000
          name: object-storage
        - containerPort: 8080
          name: console
        args:
        - server
        - --console-address
        - ":8080"
        - http://minio-{0...3}.minio/data
        volumeMounts:
        - name: minio-data
          mountPath: /data
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            scheme: HTTP
            path: /minio/health/live
            port: 9000

  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      storageClassName: ocs-external-storagecluster-ceph-rbd
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
